### ISSUE TITLE
unable find dcnnt server if using hotspot from android devices

### ISSUE THREAD

**Issue by mnabila** [cyanomiko/dcnnt-android#16]
at home I only have a network setup like this

mobile hostpot (android device) >> laptop(using arclinux)

if mobile hostpot activated dcnnt-android can't find my dcnnt server on laptop

**Comment by cyanomiko** [comment]
Finally, this bug seems fixed in 4da94c8441e21ce94fe96f23401e3d240e9e4e73 . Thanks for report!

**Comment by mnabila** [comment]
on laptopi was try install dcnnt from pypi with command ( still use archlinux distro)
`$ pip install --user dcnnt`
and run dcnnt server with foreground mode ( i want see dcnnt log)
`$ dcnnt foreground`

and on mobile (already activate mobile hotstop) i was download dcnn android from fdroid with lates version (0.7.2) but dcnnt server still not availabe on device list. 


ps: i was try dcnnt server and client using another network (use access point router) its work perfectly
